name: publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build Lib
        run: npm run build
      - name: Publish
        run: npm publish dist/ngx-english-only --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}